name: Reusable UI Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      publish:
        required: false
        type: boolean
        default: false
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: inputs.publish
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '24.7.0'
          cache: 'npm'
          cache-dependency-path: './ui/package-lock.json'

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        working-directory: ./ui
        run: npm ci

      - name: Build Shared
        working-directory: ./ui
        run: make build-protos

      - name: Package Proxy
        working-directory: ./ui
        run: make package-proxy

      - name: Package UI
        working-directory: ./ui
        run: make package

      - name: Release Proxy
        if: inputs.publish
        working-directory: ./ui
        run: make release-proxy

      - name: Release UI
        if: inputs.publish
        working-directory: ./ui
        run: make release