name: Reusable Client Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      build_type:
        required: true
        type: string # 'debug' or 'release'
      publish:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt

      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.11.7

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Shared
        working-directory: ./shared
        run: make compile publish

      - name: Lint
        working-directory: ./client
        run: make lint

      - name: Test
        working-directory: ./client
        run: make test

      # Enable hardware virtualisation - speeds up emulator
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Integration Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          target: default
          profile: pixel_6
          heap-size: 512M
          ram-size: 4096M
          emulator-boot-timeout: 600
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          working-directory: ./client
          script: make integration-test

      - name: Decode Keystore
        if: inputs.publish
        working-directory: ./client
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > release.jks

      - name: Build Debug
        if: inputs.build_type == 'debug'
        working-directory: ./client
        run: make VERSION="${{ inputs.version }}" build-debug

      - name: Build Release
        if: inputs.build_type == 'release'
        working-directory: ./client
        run: make VERSION="${{ inputs.version }}" build-release
        env:
          KEYSTORE_PATH: '../release.jks'
          KEYSTORE_PASSWORD: '${{ secrets.ANDROID_KEYSTORE_PASSWORD }}'
          KEY_ALIAS: '${{ secrets.ANDROID_KEYSTORE_ALIAS }}'

      - name: Release
        if: inputs.publish
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ inputs.build_type }}
          path: client/app/build/outputs/apk/${{ inputs.build_type }}/*.apk