name: PR Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      client: ${{ steps.filter.outputs.client }}
      ui: ${{ steps.filter.outputs.ui }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            server:
              - 'shared/**'
              - 'server/**'
            client:
              - 'shared/**'
              - 'client/**'
            ui:
              - 'shared/**'
              - 'ui/**'

  build-server:
    needs: changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    uses: ./.github/workflows/build-server.yml
    with:
      version: "pr-${{ github.event.number }}"
      publish: false
    secrets: inherit

  build-client:
    needs: changes
    if: ${{ needs.changes.outputs.client == 'true' }}
    uses: ./.github/workflows/build-client.yml
    with:
      version: "1.0.0-PR${{ github.event.number }}"
      build_type: "debug"
      publish: false
    secrets: inherit

  build-ui:
    ui-pr:
    needs: changes
    if: ${{ needs.changes.outputs.ui == 'true' }}
    uses: ./.github/workflows/build-ui.yml
    with:
      version: "pr-${{ github.event.number }}"
      publish: false
    secrets: inherit