name: Release

on:
  push:
    tags: [ "v*" ]

jobs:
  build-server:
    uses: ./.github/workflows/build-server.yml
    with:
      version: ${{ github.ref_name }}
      publish: true
    secrets: inherit

  build-client:
    uses: ./.github/workflows/build-client.yml
    with:
      version: ${{ github.ref_name }}
      build_type: "release"
      publish: true
    secrets: inherit

  build-ui:
    uses: ./.github/workflows/build-ui.yml
    with:
      version: ${{ github.ref_name }}
      publish: true
    secrets: inherit

  create-release:
    needs:
      - build-server
      - build-client
      - build-ui
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-release
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*.apk
          generate_release_notes: true